In [2]:
# import required library
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

## 1. 전처리

### **데이터 불러오기**

In [3]:
# read data
aum_m7 = pd.read_csv('../data/rawdata/aum_train/aum_m7.csv')
aum_m8 = pd.read_csv('../data/rawdata/aum_train/aum_m8.csv')
aum_m9 = pd.read_csv('../data/rawdata/aum_train/aum_m9.csv')
aum_m10 = pd.read_csv('../data/rawdata/aum_train/aum_m10.csv')
aum_m11 = pd.read_csv('../data/rawdata/aum_train/aum_m11.csv')
aum_m12 = pd.read_csv('../data/rawdata/aum_train/aum_m12.csv')

behavior_m7 = pd.read_csv('../data/rawdata/behavior_train/behavior_m7.csv')
behavior_m8 = pd.read_csv('../data/rawdata/behavior_train/behavior_m8.csv')
behavior_m9 = pd.read_csv('../data/rawdata/behavior_train/behavior_m9.csv')
behavior_m10 = pd.read_csv('../data/rawdata/behavior_train/behavior_m10.csv')
behavior_m11 = pd.read_csv('../data/rawdata/behavior_train/behavior_m11.csv')
behavior_m12 = pd.read_csv('../data/rawdata/behavior_train/behavior_m12.csv')

big_event_Q3 = pd.read_csv('../data/rawdata/big_event_train/big_event_Q3.csv')
big_event_Q4 = pd.read_csv('../data/rawdata/big_event_train/big_event_Q4.csv')

cunkuan_m7 = pd.read_csv('../data/rawdata/cunkuan_train/cunkuan_m7.csv')
cunkuan_m8 = pd.read_csv('../data/rawdata/cunkuan_train/cunkuan_m8.csv')
cunkuan_m9 = pd.read_csv('../data/rawdata/cunkuan_train/cunkuan_m9.csv')
cunkuan_m10 = pd.read_csv('../data/rawdata/cunkuan_train/cunkuan_m10.csv')
cunkuan_m11 = pd.read_csv('../data/rawdata/cunkuan_train/cunkuan_m11.csv')
cunkuan_m12 = pd.read_csv('../data/rawdata/cunkuan_train/cunkuan_m12.csv')

cust_info_q3 = pd.read_csv('../data/rawdata/cust_info_train/cust_info_q3.csv')
cust_info_q4 = pd.read_csv('../data/rawdata/cust_info_train/cust_info_q4.csv')

y_Q3_3 = pd.read_csv('../data/rawdata/train_label/y_Q3_3.csv')
y_Q4_3 = pd.read_csv('../data/rawdata/train_label/y_Q4_3.csv')

/var/folders/1b/s6dx4hpn77n6jn657xm36s300000gn/T/ipykernel_26972/3554413285.py:16: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  big_event_Q3 = pd.read_csv('../data/rawdata/big_event_train/big_event_Q3.csv')

In [4]:
# print data shape
print("aum_m7 shape: ", aum_m7.shape)
print("aum_m8 shape: ", aum_m8.shape)
print("aum_m9 shape: ", aum_m9.shape)
print("aum_m10 shape: ", aum_m10.shape)
print("aum_m11 shape: ", aum_m11.shape)
print("aum_m12 shape: ", aum_m12.shape)

print("behavior_m7 shape: ", behavior_m7.shape)
print("behavior_m8 shape: ", behavior_m8.shape)
print("behavior_m9 shape: ", behavior_m9.shape)
print("behavior_m10 shape: ", behavior_m10.shape)
print("behavior_m11 shape: ", behavior_m11.shape)
print("behavior_m12 shape: ", behavior_m12.shape)

print("big_event_Q3 shape: ", big_event_Q3.shape)
print("big_event_Q4 shape: ", big_event_Q4.shape)

print("cunkuan_m7 shape: ", cunkuan_m7.shape)
print("cunkuan_m8 shape: ", cunkuan_m8.shape)
print("cunkuan_m9 shape: ", cunkuan_m9.shape)
print("cunkuan_m10 shape: ", cunkuan_m10.shape)
print("cunkuan_m11 shape: ", cunkuan_m11.shape)
print("cunkuan_m12 shape: ", cunkuan_m12.shape)

print("cust_info_q3 shape: ", cust_info_q3.shape)
print("cust_info_q4 shape: ", cust_info_q4.shape)

print("y_Q3_3 shape: ", y_Q3_3.shape)
print("y_Q4_3 shape: ", y_Q4_3.shape)

aum_m7 shape:  (465441, 9)
aum_m8 shape:  (479063, 9)
aum_m9 shape:  (493441, 9)
aum_m10 shape:  (506513, 9)
aum_m11 shape:  (521566, 9)
aum_m12 shape:  (543823, 9)
behavior_m7 shape:  (465441, 6)
behavior_m8 shape:  (479063, 6)
behavior_m9 shape:  (493441, 8)
behavior_m10 shape:  (506513, 6)
behavior_m11 shape:  (521566, 6)
behavior_m12 shape:  (543823, 8)
big_event_Q3 shape:  (493441, 19)
big_event_Q4 shape:  (543823, 19)
cunkuan_m7 shape:  (181220, 3)
cunkuan_m8 shape:  (190278, 3)
cunkuan_m9 shape:  (200711, 3)
cunkuan_m10 shape:  (209862, 3)
cunkuan_m11 shape:  (219928, 3)
cunkuan_m12 shape:  (237042, 3)
cust_info_q3 shape:  (493441, 21)
cust_info_q4 shape:  (543823, 21)
y_Q3_3 shape:  (69126, 2)
y_Q4_3 shape:  (76170, 2)

### **테이블 병합하기**

- 모든 테이블에서 label이 있는 데이터만 남기고 행 삭제. 즉, y_Q3_3, y_Q4_3에 존재하는 'cust_no'에 해당하지 않는 데이터 행 삭제

In [5]:
# y label merge and get cust_no in y_train
y_Q3_3.rename(columns={'cust_no':'cust_no', 'label':'label_Q3'}, inplace=True)
y_Q4_3.rename(columns={'cust_no':'cust_no', 'label':'label_Q4'}, inplace=True)
y_train = pd.merge(y_Q3_3, y_Q4_3, on='cust_no', how='outer')
y_train_idx = y_train.cust_no

In [6]:
# remove row data that not in y_train_idx

# aum table
aum_m7 = aum_m7[aum_m7.cust_no.isin(y_train_idx)]
aum_m8 = aum_m8[aum_m8.cust_no.isin(y_train_idx)]
aum_m9 = aum_m9[aum_m9.cust_no.isin(y_train_idx)]
aum_m10 = aum_m10[aum_m10.cust_no.isin(y_train_idx)]
aum_m11 = aum_m11[aum_m11.cust_no.isin(y_train_idx)]
aum_m12 = aum_m12[aum_m12.cust_no.isin(y_train_idx)]

# behavior table
behavior_m7 = behavior_m7[behavior_m7.cust_no.isin(y_train_idx)]
behavior_m8 = behavior_m8[behavior_m8.cust_no.isin(y_train_idx)]
behavior_m9 = behavior_m9[behavior_m9.cust_no.isin(y_train_idx)]
behavior_m10 = behavior_m10[behavior_m10.cust_no.isin(y_train_idx)]
behavior_m11 = behavior_m11[behavior_m11.cust_no.isin(y_train_idx)]
behavior_m12 = behavior_m12[behavior_m12.cust_no.isin(y_train_idx)]

# big_event table
big_event_Q3 = big_event_Q3[big_event_Q3.cust_no.isin(y_train_idx)]
big_event_Q4 = big_event_Q4[big_event_Q4.cust_no.isin(y_train_idx)]

# cunkuan table
cunkuan_m7 = cunkuan_m7[cunkuan_m7.cust_no.isin(y_train_idx)]
cunkuan_m8 = cunkuan_m8[cunkuan_m8.cust_no.isin(y_train_idx)]
cunkuan_m9 = cunkuan_m9[cunkuan_m9.cust_no.isin(y_train_idx)]
cunkuan_m10 = cunkuan_m10[cunkuan_m10.cust_no.isin(y_train_idx)]
cunkuan_m11 = cunkuan_m11[cunkuan_m11.cust_no.isin(y_train_idx)]
cunkuan_m12 = cunkuan_m12[cunkuan_m12.cust_no.isin(y_train_idx)]

# cust_info table
cust_info_q3 = cust_info_q3[cust_info_q3.cust_no.isin(y_train_idx)]
cust_info_q4 = cust_info_q4[cust_info_q4.cust_no.isin(y_train_idx)]

In [7]:
# rename for merge
aum_m7 = aum_m7.rename(columns={'X1':'X1_m7', 'X2':'X2_m7', 'X3':'X3_m7', 'X4':'X4_m7', 'X5':'X5_m7', 'X6':'X6_m7', 'X7':'X7_m7', 'X8':'X8_m7'})
aum_m8 = aum_m8.rename(columns={'X1':'X1_m8', 'X2':'X2_m8', 'X3':'X3_m8', 'X4':'X4_m8', 'X5':'X5_m8', 'X6':'X6_m8', 'X7':'X7_m8', 'X8':'X8_m8'})
aum_m9 = aum_m9.rename(columns={'X1':'X1_m9', 'X2':'X2_m9', 'X3':'X3_m9', 'X4':'X4_m9', 'X5':'X5_m9', 'X6':'X6_m9', 'X7':'X7_m9', 'X8':'X8_m9'})
aum_m10 = aum_m10.rename(columns={'X1':'X1_m10', 'X2':'X2_m10', 'X3':'X3_m10', 'X4':'X4_m10', 'X5':'X5_m10', 'X6':'X6_m10', 'X7':'X7_m10', 'X8':'X8_m10'})
aum_m11 = aum_m11.rename(columns={'X1':'X1_m11', 'X2':'X2_m11', 'X3':'X3_m11', 'X4':'X4_m11', 'X5':'X5_m11', 'X6':'X6_m11', 'X7':'X7_m11', 'X8':'X8_m11'})
aum_m12 = aum_m12.rename(columns={'X1':'X1_m12', 'X2':'X2_m12', 'X3':'X3_m12', 'X4':'X4_m12', 'X5':'X5_m12', 'X6':'X6_m12', 'X7':'X7_m12', 'X8':'X8_m12'})

behavior_m7 = behavior_m7.rename(columns={'B1':'B1_m7', 'B2':'B2_m7', 'B3':'B3_m7', 'B4':'B4_m7', 'B5':'B5_m7'})
behavior_m8 = behavior_m8.rename(columns={'B1':'B1_m8', 'B2':'B2_m8', 'B3':'B3_m8', 'B4':'B4_m8', 'B5':'B5_m8'})
behavior_m9 = behavior_m9.rename(columns={'B1':'B1_m9', 'B2':'B2_m9', 'B3':'B3_m9', 'B4':'B4_m9', 'B5':'B5_m9', 'B6':'B6_m9', 'B7':'B7_m9'})
behavior_m10 = behavior_m10.rename(columns={'B1':'B1_m10', 'B2':'B2_m10', 'B3':'B3_m10', 'B4':'B4_m10', 'B5':'B5_m10'})
behavior_m11 = behavior_m11.rename(columns={'B1':'B1_m11', 'B2':'B2_m11', 'B3':'B3_m11', 'B4':'B4_m11', 'B5':'B5_m11'})
behavior_m12 = behavior_m12.rename(columns={'B1':'B1_m12', 'B2':'B2_m12', 'B3':'B3_m12', 'B4':'B4_m12', 'B5':'B5_m12', 'B6':'B6_m12', 'B7':'B7_m12'})

cunkuan_m7 = cunkuan_m7.rename(columns = {'C1':'C1_m7', 'C2':'C2_m7'})
cunkuan_m8 = cunkuan_m8.rename(columns = {'C1':'C1_m8', 'C2':'C2_m8'})
cunkuan_m9 = cunkuan_m9.rename(columns = {'C1':'C1_m9', 'C2':'C2_m9'})
cunkuan_m10 = cunkuan_m10.rename(columns = {'C1':'C1_m10', 'C2':'C2_m10'})
cunkuan_m11 = cunkuan_m11.rename(columns = {'C1':'C1_m11', 'C2':'C2_m11'})
cunkuan_m12 = cunkuan_m12.rename(columns = {'C1':'C1_m12', 'C2':'C2_m12'})


big_event_Q3 = big_event_Q3.rename(columns = {'E1':'E1_Q3', 'E2':'E2_Q3', 'E3':'E3_Q3', 'E4':'E4_Q3',
                                              'E5':'E5_Q3', 'E6':'E6_Q3', 'E7':'E7_Q3', 'E8':'E8_Q3',
                                              'E9':'E9_Q3', 'E10':'E10_Q3', 'E11':'E11_Q3', 'E12':'E12_Q3',
                                              'E13':'E13_Q3', 'E14':'E14_Q3', 'E15':'E15_Q3', 'E16':'E16_Q3',
                                              'E17':'E17_Q3', 'E18':'E18_Q3'})
big_event_Q4 = big_event_Q4.rename(columns = {'E1':'E1_Q4', 'E2':'E2_Q4', 'E3':'E3_Q4', 'E4':'E4_Q4',
                                                'E5':'E5_Q4', 'E6':'E6_Q4', 'E7':'E7_Q4', 'E8':'E8_Q4',
                                                'E9':'E9_Q4', 'E10':'E10_Q4', 'E11':'E11_Q4', 'E12':'E12_Q4',
                                                'E13':'E13_Q4', 'E14':'E14_Q4', 'E15':'E15_Q4', 'E16':'E16_Q4',
                                                'E17':'E17_Q4', 'E18':'E18_Q4'})

cust_info_q3 = cust_info_q3.rename(columns = {'I1':'I1_Q3', 'I2':'I2_Q3', 'I3':'I3_Q3', 'I4':'I4_Q3',
                                    'I5':'I5_Q3', 'I6':'I6_Q3', 'I7':'I7_Q3', 'I8':'I8_Q3',
                                    'I9':'I9_Q3', 'I10':'I10_Q3', 'I11':'I11_Q3', 'I12':'I12_Q3',
                                    'I13':'I13_Q3', 'I14':'I14_Q3', 'I15':'I15_Q3', 'I16':'I16_Q3',
                                    'I17':'I17_Q3', 'I18':'I18_Q3', 'I19':'I19_Q3', 'I20':'I20_Q3'})
cust_info_q4 = cust_info_q4.rename(columns = {'I1':'I1_Q4', 'I2':'I2_Q4', 'I3':'I3_Q4', 'I4':'I4_Q4',
                                    'I5':'I5_Q4', 'I6':'I6_Q4', 'I7':'I7_Q4', 'I8':'I8_Q4',
                                    'I9':'I9_Q4', 'I10':'I10_Q4', 'I11':'I11_Q4', 'I12':'I12_Q4',
                                    'I13':'I13_Q4', 'I14':'I14_Q4', 'I15':'I15_Q4', 'I16':'I16_Q4',
                                    'I17':'I17_Q4', 'I18':'I18_Q4', 'I19':'I19_Q4', 'I20':'I20_Q4'})

In [8]:
# merge table

# aum
aum_m = pd.merge(aum_m7, aum_m8, on='cust_no', how='outer')
aum_m = pd.merge(aum_m, aum_m9, on='cust_no', how='outer')
aum_m = pd.merge(aum_m, aum_m10, on='cust_no', how='outer')
aum_m = pd.merge(aum_m, aum_m11, on='cust_no', how='outer')
aum_m = pd.merge(aum_m, aum_m12, on='cust_no', how='outer')

del aum_m7, aum_m8, aum_m9, aum_m10, aum_m11, aum_m12


# behavior
behavior_m = pd.merge(behavior_m7, behavior_m8, on='cust_no', how='outer')
behavior_m = pd.merge(behavior_m, behavior_m9, on='cust_no', how='outer')
behavior_m = pd.merge(behavior_m, behavior_m10, on='cust_no', how='outer')
behavior_m = pd.merge(behavior_m, behavior_m11, on='cust_no', how='outer')
behavior_m = pd.merge(behavior_m, behavior_m12, on='cust_no', how='outer')

del behavior_m7, behavior_m8, behavior_m9, behavior_m10, behavior_m11, behavior_m12

# cunkuan
cunkuan_m = pd.merge(cunkuan_m7, cunkuan_m8, on='cust_no', how='outer')
cunkuan_m = pd.merge(cunkuan_m, cunkuan_m9, on='cust_no', how='outer')
cunkuan_m = pd.merge(cunkuan_m, cunkuan_m10, on='cust_no', how='outer')
cunkuan_m = pd.merge(cunkuan_m, cunkuan_m11, on='cust_no', how='outer')
cunkuan_m = pd.merge(cunkuan_m, cunkuan_m12, on='cust_no', how='outer')

del cunkuan_m7, cunkuan_m8, cunkuan_m9, cunkuan_m10, cunkuan_m11, cunkuan_m12


# big_event
big_event_Q = pd.merge(big_event_Q3, big_event_Q4, on='cust_no', how='outer')

del big_event_Q3, big_event_Q4


# cust_info
cust_info_q = pd.merge(cust_info_q3, cust_info_q4, on='cust_no', how='outer')

del cust_info_q3, cust_info_q4

In [9]:
# check table shape
print(aum_m.shape)       # 82899
print(behavior_m.shape)  # 82899
print(cunkuan_m.shape)   # 82896
print(big_event_Q.shape) # 82899
print(cust_info_q.shape) # 82899

(82899, 49)
(82899, 35)
(82896, 13)
(82899, 37)
(82899, 41)

#### **aum table**

**변수 설명**
- X1 : structured deposit balance(구조화 예금 잔액)
    - 금리, 환률, 지수 등의 변동이나 기업의 신용에 연동된 금융파생상품을 시중은행이 흡수하여, 고객이 일정한 금액을 받아 그에 상응하는 수익을 얻을 수 있도록 하는 예금
- X2 : time deposit balance (정기 예금 잔액)
    - 적금과 비슷한 형태의 예금
- X3 : demand deposit balance (입출금 통장 잔액)
    - 은행에 사전 통지 없이 요청 시 인출할 수 있는 은행 예금
- X4 : financial products balance (금융 상품 잔액)
- X5 : fund balance (펀드 잔액)
- X6 : asset management balance (자산 관리 잔액)
- X7 : loan balance (대출 잔액)
- X8 : large deposit certificate balance (거액 예금 증서 잔액)
    - 일정 기간 동안 고정된 금액을 보유하고 그 대가로 개설 은행에서 이자를 지급하는 예금 계좌. 예금 증서(CD)를 현금으로 바꾸거나 상환하면 원래 투자한 금액과 이자를 받게 된다.


**결측치 형태**

| cust_no   | m7                                   | m8   | m9   | m10  | m11  | m12  |
|-----------|--------------------------------------|------|------|------|------|------|
| 7월 이전 고객  | data                                 | data | data | data | data | data |
| 8월 신규 고객  | <span style="color:red"> nan </span> | data | data | data | data | data |
| 9월 신규 고객  | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | data | data | data | data |
| 10월 신규 고객 | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> |<span style="color:red"> nan </span> | data | data | data |
| 11월 신규 고객 | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span> | data | data |
| 12월 신규 고객 | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span> | data |
| 결측수 | 13485 | 10385 | 7132 | 4674 | 2239 | 0 |



**결측치 처리 방법**

- aum table 내의 변수는 은행 상품에 대한 잔액을 나타내는 변수이므로 새롭게 8월 이후에 들어온 신규 고객이 가진 결측치를 0으로 채우는 것이 타당하다고 판단함.

### **결측치 처리하기**

In [10]:
# check # of missing values by column
aum_m.isnull().sum()

cust_no        0
X1_m7      13485
X2_m7      13485
X3_m7      13485
X4_m7      13485
X5_m7      13485
X6_m7      13485
X7_m7      13485
X8_m7      13485
X1_m8      10385
X2_m8      10385
X3_m8      10385
X4_m8      10385
X5_m8      10385
X6_m8      10385
X7_m8      10385
X8_m8      10385
X1_m9       7132
X2_m9       7132
X3_m9       7132
X4_m9       7132
X5_m9       7132
X6_m9       7132
X7_m9       7132
X8_m9       7132
X1_m10      4674
X2_m10      4674
X3_m10      4674
X4_m10      4674
X5_m10      4674
X6_m10      4674
X7_m10      4674
X8_m10      4674
X1_m11      2239
X2_m11      2239
X3_m11      2239
X4_m11      2239
X5_m11      2239
X6_m11      2239
X7_m11      2239
X8_m11      2239
X1_m12         0
X2_m12         0
X3_m12         0
X4_m12         0
X5_m12         0
X6_m12         0
X7_m12         0
X8_m12         0
dtype: int64

In [11]:
# fill missing values with zeros
aum_m.fillna(0, inplace = True)

In [12]:
# check # of missing values by column
aum_m.isnull().sum()

cust_no    0
X1_m7      0
X2_m7      0
X3_m7      0
X4_m7      0
X5_m7      0
X6_m7      0
X7_m7      0
X8_m7      0
X1_m8      0
X2_m8      0
X3_m8      0
X4_m8      0
X5_m8      0
X6_m8      0
X7_m8      0
X8_m8      0
X1_m9      0
X2_m9      0
X3_m9      0
X4_m9      0
X5_m9      0
X6_m9      0
X7_m9      0
X8_m9      0
X1_m10     0
X2_m10     0
X3_m10     0
X4_m10     0
X5_m10     0
X6_m10     0
X7_m10     0
X8_m10     0
X1_m11     0
X2_m11     0
X3_m11     0
X4_m11     0
X5_m11     0
X6_m11     0
X7_m11     0
X8_m11     0
X1_m12     0
X2_m12     0
X3_m12     0
X4_m12     0
X5_m12     0
X6_m12     0
X7_m12     0
X8_m12     0
dtype: int64

#### **behavior table**

**변수 설명**
- B1 : mobile banking login times (로그인 횟수)
- B2 : transfer-in times (입금 횟수)
- B3 : transfer-in money amount (입금 금액)
- B4 : transfer-out times (출금 횟수)
- B5 : transfer-out money amount (출금 금액)
- B6 : latest transfer time (마지막 거래 시간) (type : date) (9, 12월에만 존재)
- B7 : number of transfers in a season (해당 시즌에 거래 횟수) (9, 12월에만 존재)

**결측치 형태(B1 ~ B5, B7)**

| cust_no   | m7                                   | m8   | m9   | m10  | m11  | m12  |
|-----------|--------------------------------------|------|------|------|------|------|
| 7월 이전 고객  | data                                 | data | data | data | data | data |
| 8월 신규 고객  | <span style="color:red"> nan </span> | data | data | data | data | data |
| 9월 신규 고객  | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | data | data | data | data |
| 10월 신규 고객 | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> |<span style="color:red"> nan </span> | data | data | data |
| 11월 신규 고객 | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span> | data | data |
| 12월 신규 고객 | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span>  | <span style="color:red"> nan </span> | data |
| 결측수 | 13485 | 10385 | 7132 | 4674 | 2239 | 0 |



**결측치 처리 방법(B1 ~ B5, B7)**

- behavior table 내의 변수는 은행을 사용한 행동의 횟수, 행동에 대한 금액을 나타내는 변수이므로 새롭게 8월 이후에 들어온 신규 고객이 가진 결측치를 0으로 채우는 것이 타당하다고 판단함.

**결측치 처리 방법(B6)**

- B6 변수는 마지막 거래 날짜를 의미하므로 B2, B4가 0이 아닌 마지막 시점으로 결측치를 대체한다.

In [13]:
behavior_m.isna().sum()

cust_no        0
B1_m7      13485
B2_m7      13485
B3_m7      13485
B4_m7      13485
B5_m7      13485
B1_m8      10385
B2_m8      10385
B3_m8      10385
B4_m8      10385
B5_m8      10385
B1_m9       7132
B2_m9       7132
B3_m9       7132
B4_m9       7132
B5_m9       7132
B6_m9      13909
B7_m9       7132
B1_m10      4674
B2_m10      4674
B3_m10      4674
B4_m10      4674
B5_m10      4674
B1_m11      2239
B2_m11      2239
B3_m11      2239
B4_m11      2239
B5_m11      2239
B1_m12         0
B2_m12         0
B3_m12         0
B4_m12         0
B5_m12         0
B6_m12      3932
B7_m12         0
dtype: int64

In [14]:
# Q. B7변수가 해당 분기의 3개월 간의 B2, B4 변수의 단순 합인가? (no)
# behavior_m[['B1_m7','B1_m8','B1_m9','B2_m7', 'B2_m8', 'B2_m9', 'B4_m7', 'B4_m8', 'B4_m9','B7_m9']]

In [15]:
# B6 : B2, B4가 0이 아닌 마지막 달의 1일로 결측치 채우기

def fill_last_month7to9(row_data):
    l_month = 7
    for m in range(7, 10):
        value1 = eval('row_data.B2_m' + str(m))
        value2 = eval("row_data.B4_m" + str(m))
        if ((value1 != 0) and (str(value1) != 'nan')) | ((value2 != 0) and (str(value2) != 'nan')):
            l_month = m
    return pd.datetime(2019, l_month, 1).strftime("%Y-%m-%d %H:%M:%S")


def fill_last_month7to12(row_data):
    l_month = 7
    for m in range(7, 12):
        value1 = eval('row_data.B2_m' + str(m))
        value2 = eval("row_data.B4_m" + str(m))
        if ((value1 != 0) and (str(value1) != 'nan')) | ((value2 != 0) and (str(value2) != 'nan')):
            l_month = m
    return pd.datetime(2019, l_month, 1).strftime("%Y-%m-%d %H:%M:%S")

In [16]:
behavior_m.loc[behavior_m.B6_m9.isna(), 'B6_m9'] = behavior_m[behavior_m.B6_m9.isna()].apply(fill_last_month7to9, axis = 1)
behavior_m.loc[behavior_m.B6_m12.isna(), 'B6_m12'] = behavior_m[behavior_m.B6_m12.isna()].apply(fill_last_month7to12, axis=1)

In [17]:
# fill missing data with zeros
behavior_m.fillna(0,inplace = True)

In [18]:
# behavior_m[['B6_m9','B6_m12']]

In [19]:
# check missing data
behavior_m.isna().sum()

cust_no    0
B1_m7      0
B2_m7      0
B3_m7      0
B4_m7      0
B5_m7      0
B1_m8      0
B2_m8      0
B3_m8      0
B4_m8      0
B5_m8      0
B1_m9      0
B2_m9      0
B3_m9      0
B4_m9      0
B5_m9      0
B6_m9      0
B7_m9      0
B1_m10     0
B2_m10     0
B3_m10     0
B4_m10     0
B5_m10     0
B1_m11     0
B2_m11     0
B3_m11     0
B4_m11     0
B5_m11     0
B1_m12     0
B2_m12     0
B3_m12     0
B4_m12     0
B5_m12     0
B6_m12     0
B7_m12     0
dtype: int64

#### **cunkuan table**

**변수 설명**
- C1 : deposit products value (예금 상품 가치)
    - 결측치 0으로 대체
- C2 : number of deposit products (예금 상품 수)
    - 결측치 0으로 대체

**결측치 형태**

| cust_no   | m7                                   | m8                                   | m9                                   | m10                                  | m11                                  | m12  |
|-----------|--------------------------------------|--------------------------------------|--------------------------------------|--------------------------------------|--------------------------------------|------|
| 7월 이전 고객  | data                                 | data                                 | data                                 | data                                 | data                                 | data |
| 8월 신규 고객  | <span style="color:red"> nan </span> | data                                 | data                                 | data                                 | data                                 | data |
| 9월 신규 고객  | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | data                                 | data                                 | data                                 | data |
| 10월 신규 고객 | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | data                                 | data                                 | data |
| 11월 신규 고객 | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | data                                 | data |
| 12월 신규 고객 | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | <span style="color:red"> nan </span> | data |
| 결측수 | 15296 | 12157 | 8623  | 5803 | 2822 | 0 |



**결측치 처리 방법**

- cunkuan table 내의 변수는 예금 상품 가치 상품 수를 나타내는 변수이므로 새롭게 8월 이후에 들어온 신규 고객이 가진 결측치를 0으로 채우는 것이 타당하다고 판단함.

In [20]:
# check missing values
cunkuan_m.isna().sum()

cust_no        0
C1_m7      15296
C2_m7      15296
C1_m8      12157
C2_m8      12157
C1_m9       8623
C2_m9       8623
C1_m10      5803
C2_m10      5803
C1_m11      2822
C2_m11      2822
C1_m12         0
C2_m12         0
dtype: int64

In [21]:
# fill missing values with zeros
cunkuan_m.fillna(0, inplace=True)

In [22]:
# check missing values
cunkuan_m.isna().sum()

cust_no    0
C1_m7      0
C2_m7      0
C1_m8      0
C2_m8      0
C1_m9      0
C2_m9      0
C1_m10     0
C2_m10     0
C1_m11     0
C2_m11     0
C1_m12     0
C2_m12     0
dtype: int64

#### **big_event table**

**변수 설명**

- E1 : account opening date (계좌 오픈 날짜)
- E2 : online banking opening date (온라인 뱅킹 오픈 날짜)
- E3 : mobile banking opening date (모바일 뱅킹 오픈 날짜)
- E4 : first online banking login date (첫번째 온라인 뱅킹 로그인 날짜)
- E5 : first mobile banking login date (첫번째 모바일 뱅킹 로그인 날짜)
- E6 : first demand deposit date (첫번째 입출금 날짜)
- E7 : first time deposit date (최초 입금 일)
- E8 : first loan date (최초 대출 일)
- E9 : first overdue date (최초 연체 날짜)
- E10 : first cash transaction date (최초 현금 거래일)
- E11 : first bank-securities transfer date (최초 은행 - 증권 이체 날짜)
- E12 : first transfer at counter date (최초 카운터에서 이체 날짜)
- E13 : first transfer via online banking date (온라인 뱅킹을 이용한 최초 이체 날짜)
- E14 : first transfer via mobile banking date (모바일 뱅킹을 이용한 최초 이체 날짜)
- E15 : maximum amount transferred out of another bank (다른 은행에서 이체된 최대 금액)
- E16 : maximum amount transferred out of another bank date (다른 은행에서 이체된 최대 금액이 이체된 날짜)
- E17 : Maximum transfer amount from other bank (타 은행 최대 이체 금액)
- E18 : Maximum transfer amount from other bank date (타 은행 최대 이체 금액 이체 날짜)

**결측치 처리 방법**

- Q3, Q4 분리 후 처리. 아래에서 다시 다룸.

#### **cust_info table**

**변수 설명**
- l1 : gender (성별)
- l2 : age (나이)
- l3 : class
- l4 : tag
- I5 : occupation (직업)
- I6 : deposit customer tag (예금 고객 태그)
- I7 : number of products owning (보유 제품 수)
- I8 : constellation (별자리)
- I9 : contribution (기부금)
- I10 : education level (교육 수준)
- I11 : family annual income (가구 연간 소득)
- I12 : field description
- I13 : marriage description
- I14 : occupation description
- I15 : QR code recipient
- I16 : VIP (vip 여부)
- I17 : online banking client
- I18 : mobile banking client
- I19 : SMS client
- I20 : WeChat Pay client

**결측치 처리 방법**

- I8 삭제 - 불필요한 정보
- I12 삭제 - 1행만 제외하고 가진 정보가 동일함.
- I9, I10, I13, I14 삭제 - 결측치가 너무 많음.
- 나머지 변수는 Q4의 값으로 Q3값 대체. 변하지 않는 고객 일반 정보거나, 분기별로 크게 변하지 않는 등급, 직업과 같은 정보이기 때문이다.
- I5 결측 : '무직'으로 대체

In [23]:
# del I9, I10, I13, I14
cust_info_q.drop(columns = ['I9_Q3', 'I9_Q4', 'I10_Q3', 'I10_Q4', 'I13_Q3', 'I13_Q4', 'I14_Q3', 'I14_Q4'], inplace=True)

In [24]:
# del I8, I12
cust_info_q.drop(columns = ['I8_Q3', 'I8_Q4', 'I12_Q3', 'I12_Q4'], inplace=True)

In [25]:
# Replace the value of Q3 with the value of Q4
cust_info_q.I1_Q3.fillna(cust_info_q.I1_Q4, inplace=True)
cust_info_q.I2_Q3.fillna(cust_info_q.I2_Q4, inplace=True)
cust_info_q.I3_Q3.fillna(cust_info_q.I3_Q4, inplace=True)
cust_info_q.I4_Q3.fillna(cust_info_q.I4_Q4, inplace=True)
cust_info_q.I5_Q3.fillna(cust_info_q.I5_Q4, inplace=True)
cust_info_q.I6_Q3.fillna(cust_info_q.I6_Q4, inplace=True)
cust_info_q.I7_Q3.fillna(cust_info_q.I7_Q4, inplace=True)
cust_info_q.I11_Q3.fillna(cust_info_q.I11_Q4, inplace=True)
cust_info_q.I15_Q3.fillna(cust_info_q.I15_Q4, inplace=True)
cust_info_q.I16_Q3.fillna(cust_info_q.I16_Q4, inplace=True)
cust_info_q.I17_Q3.fillna(cust_info_q.I17_Q4, inplace=True)
cust_info_q.I18_Q3.fillna(cust_info_q.I18_Q4, inplace=True)
cust_info_q.I19_Q3.fillna(cust_info_q.I19_Q4, inplace=True)
cust_info_q.I20_Q3.fillna(cust_info_q.I20_Q4, inplace=True)

In [26]:
cust_info_q.isna().sum()

cust_no       0
I1_Q3        32
I2_Q3         0
I3_Q3         0
I4_Q3         0
I5_Q3      4947
I6_Q3         0
I7_Q3         0
I11_Q3        0
I15_Q3        0
I16_Q3        0
I17_Q3        0
I18_Q3        0
I19_Q3        0
I20_Q3        0
I1_Q4        32
I2_Q4         0
I3_Q4         0
I4_Q4         0
I5_Q4      4947
I6_Q4         0
I7_Q4         0
I11_Q4        0
I15_Q4        0
I16_Q4        0
I17_Q4        0
I18_Q4        0
I19_Q4        0
I20_Q4        0
dtype: int64

In [27]:
cust_info_q.I1_Q3.value_counts()

女性    44431
男性    38436
Name: I1_Q3, dtype: int64

In [28]:
cust_info_q.I1_Q3 = cust_info_q.I1_Q3.replace({'女性':0, '男性':1})
cust_info_q.I1_Q4 = cust_info_q.I1_Q4.replace({'女性':0, '男性':1})

In [29]:
cust_info_q.I3_Q3.value_counts()

普通客户    47010
黄金      26552
白金       8508
钻石        829
Name: I3_Q3, dtype: int64

In [30]:
# cust_info_q.I3_Q3 = cust_info_q.I3_Q3.replace({'普通客户':'일반고객', '黄金':'금', '白金':'백금', '钻石':'다이아몬드'})
# cust_info_q.I3_Q4 = cust_info_q.I3_Q4.replace({'普通客户':'일반고객', '黄金':'금', '白金':'백금', '钻石':'다이아몬드'})

cust_info_q.I3_Q3 = cust_info_q.I3_Q3.replace({'普通客户':4, '黄金':3, '白金':2, '钻石':1})
cust_info_q.I3_Q4 = cust_info_q.I3_Q4.replace({'普通客户':4, '黄金':3, '白金':2, '钻石':1})

In [31]:
cust_info_q.I5_Q3.value_counts()

不便分类的其他从业人员             24770
商业工作人员                  15952
服务性工作人员                 14295
办事人员和有关人员               10977
专业技术人员                   4360
未知                       2593
生产、运输设备操作人员及有关人员         2158
国家机关、党群组织、企业、事业单位负责人     2131
农、林、牧、渔、水利业生产人员           671
军人                         40
退休                          5
Name: I5_Q3, dtype: int64

In [32]:
cust_info_q.I5_Q3 = cust_info_q.I5_Q3.replace({'不便分类的其他从业人员':'프리랜서', '商业工作人员':'판매원', '服务性工作人员':'서비스직', '专业技术人员':'전문직', '办事人员和有关人员':'사무원','未知':'무직', '生产、运输设备操作人员及有关人员':'생산직', '国家机关、党群组织、企业、事业单位负责人':'정치인','农、林、牧、渔、水利业生产人员':'농축업', '军人':'군인', '退休':'은퇴'})
cust_info_q.I5_Q4 = cust_info_q.I5_Q4.replace({'不便分类的其他从业人员':'프리랜서', '商业工作人员':'판매원', '服务性工作人员':'서비스직', '专业技术人员':'전문직', '办事人员和有关人员':'사무원','未知':'무직', '生产、运输设备操作人员及有关人员':'생산직', '国家机关、党群组织、企业、事业单位负责人':'정치인','农、林、牧、渔、水利业生产人员':'농축업', '军人':'군인', '退休':'은퇴'})

In [33]:
cust_info_q.I5_Q3.fillna('무직', inplace=True)
cust_info_q.I5_Q4.fillna('무직', inplace=True)

### **테이블 병합**

In [34]:
# check table shape
print(aum_m.shape)  # 82899
print(behavior_m.shape)  # 82899
print(cunkuan_m.shape)  # 82896
print(big_event_Q.shape)  # 82899
print(cust_info_q.shape)  # 82899
print(y_train.shape) # 82899

(82899, 49)
(82899, 35)
(82896, 13)
(82899, 37)
(82899, 29)
(82899, 3)

In [35]:
# merge table
train = pd.merge(aum_m, behavior_m, on='cust_no', how='left')
train = pd.merge(train, cunkuan_m, on='cust_no', how='left')
train = pd.merge(train, big_event_Q, on='cust_no', how='left')
train = pd.merge(train, cust_info_q, on='cust_no', how='left')
train = pd.merge(train, y_train, on='cust_no', how='left')

In [36]:
# remove rows where C1 is missing
train.dropna(subset=['C1_m11'], inplace=True)

### 테이블 분리

- Q3와 Q4로 테이블 분리

In [37]:
train.columns

Index(['cust_no', 'X1_m7', 'X2_m7', 'X3_m7', 'X4_m7', 'X5_m7', 'X6_m7',
       'X7_m7', 'X8_m7', 'X1_m8',
       ...
       'I7_Q4', 'I11_Q4', 'I15_Q4', 'I16_Q4', 'I17_Q4', 'I18_Q4', 'I19_Q4',
       'I20_Q4', 'label_Q3', 'label_Q4'],
      dtype='object', length=161)

In [38]:
Q3_col_list = ['cust_no', 'label_Q3', 'E1_Q3', 'E2_Q3', 'E3_Q3', 'E4_Q3', 'E5_Q3', 'E6_Q3', 'E7_Q3', 'E8_Q3', 'E9_Q3', 'E10_Q3', 'E11_Q3', 'E12_Q3', 'E13_Q3', 'E14_Q3', 'E15_Q3', 'E16_Q3', 'E17_Q3', 'E18_Q3', 'I1_Q3', 'I2_Q3', 'I3_Q3', 'I4_Q3', 'I5_Q3', 'I6_Q3', 'I7_Q3', 'I11_Q3', 'I15_Q3', 'I16_Q3', 'I17_Q3', 'I18_Q3', 'I19_Q3', 'I20_Q3']
Q4_col_list = ['cust_no', 'label_Q4', 'E1_Q4', 'E2_Q4', 'E3_Q4', 'E4_Q4', 'E5_Q4', 'E6_Q4', 'E7_Q4', 'E8_Q4', 'E9_Q4', 'E10_Q4', 'E11_Q4', 'E12_Q4', 'E13_Q4', 'E14_Q4', 'E15_Q4', 'E16_Q4', 'E17_Q4', 'E18_Q4', 'I1_Q4', 'I2_Q4', 'I3_Q4', 'I4_Q4', 'I5_Q4', 'I6_Q4', 'I7_Q4', 'I11_Q4', 'I15_Q4', 'I16_Q4', 'I17_Q4', 'I18_Q4', 'I19_Q4', 'I20_Q4']

for m in range(7,10):
    Q3_col_list.append('X1_m'+str(m))
    Q3_col_list.append('X2_m'+str(m))
    Q3_col_list.append('X3_m'+str(m))
    Q3_col_list.append('X4_m'+str(m))
    Q3_col_list.append('X5_m'+str(m))
    Q3_col_list.append('X6_m'+str(m))
    Q3_col_list.append('X7_m'+str(m))
    Q3_col_list.append('X8_m'+str(m))
    Q3_col_list.append('B1_m'+str(m))
    Q3_col_list.append('B2_m'+str(m))
    Q3_col_list.append('B3_m'+str(m))
    Q3_col_list.append('B4_m'+str(m))
    Q3_col_list.append('B5_m'+str(m))
    if m == 9:
        Q3_col_list.append('B6_m'+str(m))
        Q3_col_list.append('B7_m'+str(m))
    Q3_col_list.append('C1_m'+str(m))
    Q3_col_list.append('C2_m'+str(m))

for m in range(10,13):
    Q4_col_list.append('X1_m'+str(m))
    Q4_col_list.append('X2_m'+str(m))
    Q4_col_list.append('X3_m'+str(m))
    Q4_col_list.append('X4_m'+str(m))
    Q4_col_list.append('X5_m'+str(m))
    Q4_col_list.append('X6_m'+str(m))
    Q4_col_list.append('X7_m'+str(m))
    Q4_col_list.append('X8_m'+str(m))
    Q4_col_list.append('B1_m'+str(m))
    Q4_col_list.append('B2_m'+str(m))
    Q4_col_list.append('B3_m'+str(m))
    Q4_col_list.append('B4_m'+str(m))
    Q4_col_list.append('B5_m'+str(m))
    if m == 12:
        Q4_col_list.append('B6_m'+str(m))
        Q4_col_list.append('B7_m'+str(m))
    Q4_col_list.append('C1_m'+str(m))
    Q4_col_list.append('C2_m'+str(m))

In [39]:
# check
print(len(Q4_col_list))
print(len(Q3_col_list))

81
81

In [40]:
train_Q3 = train.loc[:,Q3_col_list]
train_Q4 = train.loc[:,Q4_col_list]

In [41]:
print(train_Q3.shape)
print(train_Q4.shape)

(82896, 81)
(82896, 81)

In [42]:
# remove no label data
train_Q3.dropna(subset=['label_Q3'], inplace=True)
train_Q4.dropna(subset=['label_Q4'], inplace=True)

In [43]:
print(train_Q3.shape)
print(train_Q4.shape)

(69123, 81)
(76167, 81)

In [44]:
def check_missing(dat):
    '''Print missing values in each column of the dat
    @Param df dat: input data frame
    '''
    missing_val = dat.isnull().sum()
    for index in missing_val.index:
        if missing_val[index] > 0:
            print('{} has {} missing values. ({:.4%})'.format(index, missing_val[index], missing_val[index]/dat.shape[0]))

In [45]:
check_missing(train_Q3)

E2_Q3 has 3215 missing values. (4.6511%)
E3_Q3 has 3215 missing values. (4.6511%)
E4_Q3 has 40019 missing values. (57.8953%)
E5_Q3 has 26400 missing values. (38.1928%)
E6_Q3 has 3767 missing values. (5.4497%)
E7_Q3 has 67763 missing values. (98.0325%)
E8_Q3 has 60691 missing values. (87.8015%)
E9_Q3 has 69081 missing values. (99.9392%)
E10_Q3 has 361 missing values. (0.5223%)
E11_Q3 has 69123 missing values. (100.0000%)
E12_Q3 has 58086 missing values. (84.0328%)
E13_Q3 has 60467 missing values. (87.4774%)
E14_Q3 has 42947 missing values. (62.1313%)
E16_Q3 has 32463 missing values. (46.9641%)
E18_Q3 has 29274 missing values. (42.3506%)
I1_Q3 has 32 missing values. (0.0463%)

In [46]:
check_missing(train_Q4)

E2_Q4 has 3151 missing values. (4.1370%)
E3_Q4 has 3151 missing values. (4.1370%)
E4_Q4 has 44458 missing values. (58.3691%)
E5_Q4 has 28723 missing values. (37.7106%)
E6_Q4 has 3765 missing values. (4.9431%)
E7_Q4 has 74633 missing values. (97.9860%)
E8_Q4 has 66684 missing values. (87.5497%)
E9_Q4 has 76140 missing values. (99.9646%)
E10_Q4 has 455 missing values. (0.5974%)
E11_Q4 has 76167 missing values. (100.0000%)
E12_Q4 has 63232 missing values. (83.0176%)
E13_Q4 has 67029 missing values. (88.0027%)
E14_Q4 has 47057 missing values. (61.7813%)
E16_Q4 has 36061 missing values. (47.3447%)
E18_Q4 has 32867 missing values. (43.1512%)
I1_Q4 has 32 missing values. (0.0420%)

#### **E 변수 결측치 처리**

- 결측률 70% 이상 (E7, E8, E9, E11, E12, E13) : 삭제
- 결측률 30 ~ 70% (E4, E5, E14, E16, E18) : 0, 1변수로 변환
- 결측률 30% 이하 : (기준 날짜 - value)의 max로 대체

In [47]:
# del E7, E8, E9, E11, E12, E13
train_Q3.drop(columns =['E7_Q3', 'E8_Q3', 'E9_Q3','E11_Q3', 'E12_Q3', 'E13_Q3'], inplace = True)
train_Q4.drop(columns =['E7_Q4', 'E8_Q4', 'E9_Q4','E11_Q4', 'E12_Q4', 'E13_Q4'], inplace = True)

In [48]:
train_Q3.E4_Q3 = (~train_Q3.E4_Q3.isna()).astype(int)
train_Q3.E5_Q3 = (~train_Q3.E5_Q3.isna()).astype(int)
train_Q3.E14_Q3 = (~train_Q3.E14_Q3.isna()).astype(int)
train_Q3.E16_Q3 = (~train_Q3.E16_Q3.isna()).astype(int)
train_Q3.E18_Q3 = (~train_Q3.E18_Q3.isna()).astype(int)

train_Q4.E4_Q4 = (~train_Q4.E4_Q4.isna()).astype(int)
train_Q4.E5_Q4 = (~train_Q4.E5_Q4.isna()).astype(int)
train_Q4.E14_Q4 = (~train_Q4.E14_Q4.isna()).astype(int)
train_Q4.E16_Q4 = (~train_Q4.E16_Q4.isna()).astype(int)
train_Q4.E18_Q4 = (~train_Q4.E18_Q4.isna()).astype(int)

In [49]:
def date_diff_Q3(x):
    return (pd.datetime(2019, 9, 30) - x).days

def date_diff_Q4(x):
    return (pd.datetime(2019,12,31) - x).days

In [50]:
# Convert data type to datetime
train_Q3[['E1_Q3', 'E2_Q3', 'E3_Q3', 'E6_Q3', 'E10_Q3','E14_Q3', 'E15_Q3','B6_m9']] = train_Q3[['E1_Q3', 'E2_Q3', 'E3_Q3', 'E6_Q3', 'E10_Q3','E14_Q3', 'E15_Q3','B6_m9']].apply(pd.to_datetime)

train_Q4[['E1_Q4', 'E2_Q4', 'E3_Q4', 'E6_Q4', 'E10_Q4','E14_Q4', 'E15_Q4','B6_m12']] = train_Q4[['E1_Q4', 'E2_Q4', 'E3_Q4', 'E6_Q4', 'E10_Q4','E14_Q4', 'E15_Q4','B6_m12']].apply(pd.to_datetime)

In [51]:
# fillna with max value
train_Q3.E2_Q3.fillna(train_Q3.E2_Q3.max(), inplace=True)
train_Q3.E3_Q3.fillna(train_Q3.E3_Q3.max(), inplace=True)
train_Q3.E6_Q3.fillna(train_Q3.E6_Q3.max(), inplace=True)
train_Q3.E10_Q3.fillna(train_Q3.E10_Q3.max(), inplace=True)

train_Q4.E2_Q4.fillna(train_Q4.E2_Q4.max(), inplace=True)
train_Q4.E3_Q4.fillna(train_Q4.E3_Q4.max(), inplace=True)
train_Q4.E6_Q4.fillna(train_Q4.E6_Q4.max(), inplace=True)
train_Q4.E10_Q4.fillna(train_Q4.E10_Q4.max(), inplace=True)

In [52]:
# Recency 
train_Q3['Recency'] = (train_Q3['B6_m9'] - train_Q3['E6_Q3']).dt.days
train_Q4['Recency'] = (train_Q4['B6_m12'] - train_Q4['E6_Q4']).dt.days

In [53]:
train_Q3['Time'] = (pd.datetime(2022,12,31) - train_Q3['B6_m9']).dt.days  
train_Q4['Time'] = (pd.datetime(2022,12,31) - train_Q4['B6_m12']).dt.days

In [54]:
# train_Q3[['B6_m9','E6_Q3']]

In [55]:
train_Q3[train_Q3['Recency'] < 0].shape

(3713, 77)

In [56]:
train_Q3 = train_Q3[train_Q3['Recency'] > 0]  
train_Q4 = train_Q4[train_Q4['Recency'] > 0]

In [57]:
train_Q3['last_Date'] = train_Q3['B6_m9'].copy()  
train_Q4['last_Date'] = train_Q4['B6_m12'].copy()    

train_Q3['first_Date'] = train_Q3['E6_Q3'].copy()  
train_Q4['first_Date'] = train_Q4['E6_Q4'].copy()

In [58]:
train_Q3.E1_Q3 = train_Q3.E1_Q3.apply(date_diff_Q3)
train_Q3.E2_Q3 = train_Q3.E2_Q3.apply(date_diff_Q3)
train_Q3.E3_Q3 = train_Q3.E3_Q3.apply(date_diff_Q3)
train_Q3.E6_Q3 = train_Q3.E6_Q3.apply(date_diff_Q3)
train_Q3.E10_Q3 = train_Q3.E10_Q3.apply(date_diff_Q3)
train_Q3.E14_Q3 = train_Q3.E14_Q3.apply(date_diff_Q3)
train_Q3.E15_Q3 = train_Q3.E15_Q3.apply(date_diff_Q3)
train_Q3.B6_m9 = train_Q3.B6_m9.apply(date_diff_Q3)

train_Q4.E1_Q4 = train_Q4.E1_Q4.apply(date_diff_Q4)
train_Q4.E2_Q4 = train_Q4.E2_Q4.apply(date_diff_Q4)
train_Q4.E3_Q4 = train_Q4.E3_Q4.apply(date_diff_Q4)
train_Q4.E6_Q4 = train_Q4.E6_Q4.apply(date_diff_Q4)
train_Q4.E10_Q4 = train_Q4.E10_Q4.apply(date_diff_Q4)
train_Q4.E14_Q4 = train_Q4.E14_Q4.apply(date_diff_Q4)
train_Q4.E15_Q4 = train_Q4.E15_Q4.apply(date_diff_Q4)
train_Q4.B6_m12 = train_Q4.B6_m12.apply(date_diff_Q4)

### Q3, Q4 table 합치기 (concatenate)

In [59]:
train_Q3.columns

Index(['cust_no', 'label_Q3', 'E1_Q3', 'E2_Q3', 'E3_Q3', 'E4_Q3', 'E5_Q3',
       'E6_Q3', 'E10_Q3', 'E14_Q3', 'E15_Q3', 'E16_Q3', 'E17_Q3', 'E18_Q3',
       'I1_Q3', 'I2_Q3', 'I3_Q3', 'I4_Q3', 'I5_Q3', 'I6_Q3', 'I7_Q3', 'I11_Q3',
       'I15_Q3', 'I16_Q3', 'I17_Q3', 'I18_Q3', 'I19_Q3', 'I20_Q3', 'X1_m7',
       'X2_m7', 'X3_m7', 'X4_m7', 'X5_m7', 'X6_m7', 'X7_m7', 'X8_m7', 'B1_m7',
       'B2_m7', 'B3_m7', 'B4_m7', 'B5_m7', 'C1_m7', 'C2_m7', 'X1_m8', 'X2_m8',
       'X3_m8', 'X4_m8', 'X5_m8', 'X6_m8', 'X7_m8', 'X8_m8', 'B1_m8', 'B2_m8',
       'B3_m8', 'B4_m8', 'B5_m8', 'C1_m8', 'C2_m8', 'X1_m9', 'X2_m9', 'X3_m9',
       'X4_m9', 'X5_m9', 'X6_m9', 'X7_m9', 'X8_m9', 'B1_m9', 'B2_m9', 'B3_m9',
       'B4_m9', 'B5_m9', 'B6_m9', 'B7_m9', 'C1_m9', 'C2_m9', 'Recency', 'Time',
       'last_Date', 'first_Date'],
      dtype='object')

In [60]:
train_Q4.columns

Index(['cust_no', 'label_Q4', 'E1_Q4', 'E2_Q4', 'E3_Q4', 'E4_Q4', 'E5_Q4',
       'E6_Q4', 'E10_Q4', 'E14_Q4', 'E15_Q4', 'E16_Q4', 'E17_Q4', 'E18_Q4',
       'I1_Q4', 'I2_Q4', 'I3_Q4', 'I4_Q4', 'I5_Q4', 'I6_Q4', 'I7_Q4', 'I11_Q4',
       'I15_Q4', 'I16_Q4', 'I17_Q4', 'I18_Q4', 'I19_Q4', 'I20_Q4', 'X1_m10',
       'X2_m10', 'X3_m10', 'X4_m10', 'X5_m10', 'X6_m10', 'X7_m10', 'X8_m10',
       'B1_m10', 'B2_m10', 'B3_m10', 'B4_m10', 'B5_m10', 'C1_m10', 'C2_m10',
       'X1_m11', 'X2_m11', 'X3_m11', 'X4_m11', 'X5_m11', 'X6_m11', 'X7_m11',
       'X8_m11', 'B1_m11', 'B2_m11', 'B3_m11', 'B4_m11', 'B5_m11', 'C1_m11',
       'C2_m11', 'X1_m12', 'X2_m12', 'X3_m12', 'X4_m12', 'X5_m12', 'X6_m12',
       'X7_m12', 'X8_m12', 'B1_m12', 'B2_m12', 'B3_m12', 'B4_m12', 'B5_m12',
       'B6_m12', 'B7_m12', 'C1_m12', 'C2_m12', 'Recency', 'Time', 'last_Date',
       'first_Date'],
      dtype='object')

In [61]:
colname = ['cust_no', 'label', 'E1', 'E2', 'E3', 'E4', 'E5',
       'E6', 'E10', 'E14', 'E15', 'E16', 'E17', 'E18',
       'I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I11',
       'I15', 'I16', 'I17', 'I18', 'I19', 'I20', 'X1_m1',
       'X2_m1', 'X3_m1', 'X4_m1', 'X5_m1', 'X6_m1', 'X7_m1', 'X8_m1', 'B1_m1',
       'B2_m1', 'B3_m1', 'B4_m1', 'B5_m1', 'C1_m1', 'C2_m1', 'X1_m2', 'X2_m2',
       'X3_m2', 'X4_m2', 'X5_m2', 'X6_m2', 'X7_m2', 'X8_m2', 'B1_m2', 'B2_m2',
       'B3_m2', 'B4_m2', 'B5_m2', 'C1_m2', 'C2_m2', 'X1_m3', 'X2_m3', 'X3_m3',
       'X4_m3', 'X5_m3', 'X6_m3', 'X7_m3', 'X8_m3', 'B1_m3', 'B2_m3', 'B3_m3',
       'B4_m3', 'B5_m3', 'B6_m3', 'B7_m3', 'C1_m3', 'C2_m3', 'Recency', 'Time', 
       'last_Date', 'first_Date']

In [62]:
train_Q3.columns = colname
train_Q4.columns = colname

In [63]:
train = pd.concat([train_Q3, train_Q4])

In [64]:
print(train.shape)
train.head()

(130654, 79)

,cust_no,label,E1,E2,E3,E4,E5,E6,E10,E14,...,B4_m3,B5_m3,B6_m3,B7_m3,C1_m3,C2_m3,Recency,Time,last_Date,first_Date
0,0xb2d30bf6,1.0,790,789,789,0,0,168,1,18169,...,0.0,0.0,18,3.0,23140.95,1.0,149,1206,2019-09-11 18:00:00,2019-04-15
1,0xb2d0c143,1.0,1538,1538,1538,1,1,353,263,18168,...,1.0,60000.0,10,21.0,170094.56,4.0,342,1198,2019-09-19 05:04:00,2018-10-12
2,0xb2d6004d,1.0,305,305,305,0,0,305,175,18169,...,0.0,0.0,163,0.0,70013.94,3.0,141,1351,2019-04-19 04:03:00,2018-11-29
3,0xb2d5a839,1.0,356,356,356,0,1,332,284,18168,...,1.0,30000.0,18,4.0,123812.32,2.0,313,1206,2019-09-11 15:40:00,2018-11-02
5,0xb2d6d3ac,-1.0,160,160,160,1,1,154,1,18168,...,3.0,500000.0,26,4.0,398.72,1.0,127,1214,2019-09-03 14:33:00,2019-04-29

In [65]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 130654 entries, 0 to 82898
Data columns (total 79 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   cust_no     130654 non-null  object
 1   label       130654 non-null  float64
 2   E1          130654 non-null  int64
 3   E2          130654 non-null  int64
 4   E3          130654 non-null  int64
 5   E4          130654 non-null  int64
 6   E5          130654 non-null  int64
 7   E6          130654 non-null  int64
 8   E10         130654 non-null  int64
 9   E14         130654 non-null  int64
 10  E15         130654 non-null  int64
 11  E16         130654 non-null  int64
 12  E17         130654 non-null  float64
 13  E18         130654 non-null  int64
 14  I1          130654 non-null  float64
 15  I2          130654 non-null  float64
 16  I3          130654 non-null  int64
 17  I4          130654 non-null  float64
 18  I5          130654 non-null  object
 19  I6          130654 non-null  float64
 20  I7          130654 non-null  float64
 21  I11         130654 non-null  float64
 22  I15         130654 non-null  float64
 23  I16         130654 non-null  float64
 24  I17         130654 non-null  float64
 25  I18         130654 non-null  float64
 26  I19         130654 non-null  float64
 27  I20         130654 non-null  float64
 28  X1_m1       130654 non-null  float64
 29  X2_m1       130654 non-null  float64
 30  X3_m1       130654 non-null  float64
 31  X4_m1       130654 non-null  float64
 32  X5_m1       130654 non-null  float64
 33  X6_m1       130654 non-null  float64
 34  X7_m1       130654 non-null  float64
 35  X8_m1       130654 non-null  float64
 36  B1_m1       130654 non-null  float64
 37  B2_m1       130654 non-null  float64
 38  B3_m1       130654 non-null  float64
 39  B4_m1       130654 non-null  float64
 40  B5_m1       130654 non-null  float64
 41  C1_m1       130654 non-null  float64
 42  C2_m1       130654 non-null  float64
 43  X1_m2       130654 non-null  float64
 44  X2_m2       130654 non-null  float64
 45  X3_m2       130654 non-null  float64
 46  X4_m2       130654 non-null  float64
 47  X5_m2       130654 non-null  float64
 48  X6_m2       130654 non-null  float64
 49  X7_m2       130654 non-null  float64
 50  X8_m2       130654 non-null  float64
 51  B1_m2       130654 non-null  float64
 52  B2_m2       130654 non-null  float64
 53  B3_m2       130654 non-null  float64
 54  B4_m2       130654 non-null  float64
 55  B5_m2       130654 non-null  float64
 56  C1_m2       130654 non-null  float64
 57  C2_m2       130654 non-null  float64
 58  X1_m3       130654 non-null  float64
 59  X2_m3       130654 non-null  float64
 60  X3_m3       130654 non-null  float64
 61  X4_m3       130654 non-null  float64
 62  X5_m3       130654 non-null  float64
 63  X6_m3       130654 non-null  float64
 64  X7_m3       130654 non-null  float64
 65  X8_m3       130654 non-null  float64
 66  B1_m3       130654 non-null  float64
 67  B2_m3       130654 non-null  float64
 68  B3_m3       130654 non-null  float64
 69  B4_m3       130654 non-null  float64
 70  B5_m3       130654 non-null  float64
 71  B6_m3       130654 non-null  int64
 72  B7_m3       130654 non-null  float64
 73  C1_m3       130654 non-null  float64
 74  C2_m3       130654 non-null  float64
 75  Recency     130654 non-null  int64
 76  Time        130654 non-null  int64
 77  last_Date   130654 non-null  datetime64[ns]
 78  first_Date  130654 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(60), int64(15), object(2)
memory usage: 79.7+ MB

In [66]:
train[train['cust_no'] == '0xb2d21060']

,cust_no,label,E1,E2,E3,E4,E5,E6,E10,E14,...,B4_m3,B5_m3,B6_m3,B7_m3,C1_m3,C2_m3,Recency,Time,last_Date,first_Date
45847,0xb2d21060,-1.0,1148,1148,1148,1,1,2,1080,18168,...,14.0,144771.55,-1,113.0,2508.19,12.0,2,1187,2019-09-30 17:23:00,2019-09-28
45847,0xb2d21060,-1.0,1240,1240,1240,1,1,39,1172,18260,...,5.0,24809.00,7,108.0,113.47,8.0,31,1103,2019-12-23 13:01:00,2019-11-22

In [67]:
train['cust_no'].value_counts()

0xb2d30bf6    2
0xb2d5ceb7    2
0xb2d0bf20    2
0xb2d1498f    2
0xb2d5ff89    2
             ..
0xb2d40000    1
0xb2d16b6a    1
0xb2d5fd22    1
0xb2d62a97    1
0xb2da17e8    1
Name: cust_no, Length: 75885, dtype: int64

### **dummy 변수 생성 (I5)**

In [68]:
# create dummy variable
train = pd.concat([train,pd.get_dummies(train.I5)], axis = 1)
train.drop(columns = ['I5'], inplace = True)
print(train.shape)

(130654, 89)

### 2. LTV 모델링 

Recency : 얼마나 최근에 구매했는가 (고객별 구매 일수)   
Frequency : 얼마나 자주 구매했는가 (고객별 첫 거래 ~ 마지막 거래까지의 시간)   
Time : 얼마나 시간이 소요되었는가 (고객별 첫 거래 ~ 집계일까지의 거래)    
Monetary : 얼마나 많은 금액을 지출했는가 (고객별 평균 구매 금액)   






1. 고객별 RFMT를 구하기
2. calibration/holdout 데이터를 나눠 L2 penalty 최적화 하기 
3. 최적화된 값을 BG/NBD 모형에 넣어 예상 구매 일수 구하기 
4. 최적화된 값을 Gamma-Gamma 모형에 넣어 예상 구매 금액을 구하기 
5. BG/NBD 모형과 Gamma-Gamma 모형을 합쳐 LTV를 구하기

### 2-1. RFTM 계산중 Monetary값에 해당되는 값 -> 차원축소 할것 
 - X1 : structured deposit balance(구조화 예금 잔액)  
- X2 : time deposit balance (정기 예금 잔액)  
- X3 : demand deposit balance (입출금 통장 잔액)  
- X4 : financial products balance (금융 상품 잔액)  
- X5 : fund balance (펀드 잔액)  
- X6 : asset management balance (자산 관리 잔액)  
- X7 : loan balance (대출 잔액)  
- X8 : large deposit certificate balance (거액 예금 증서 잔액)

In [69]:
train.head()  
train.isnull().sum() # 확인결과 I1 gender 64개의 null 값 존재함

cust_no    0
label      0
E1         0
E2         0
E3         0
          ..
은퇴         0
전문직        0
정치인        0
판매원        0
프리랜서       0
Length: 89, dtype: int64

In [70]:

from sklearn import linear_model 
lin_reg = linear_model.LogisticRegression(solver='lbfgs', max_iter=1000 )  

X = train.drop(columns = ['I1', 'cust_no', 'Recency',	'Time',	'last_Date'	,'first_Date'])   
y = train['I1']
train['I1'].value_counts()  

lin_log_model = lin_reg.fit(X, y)  
y_pred = lin_log_model.predict(X)   
train['I1'].fillna(pd.Series(y_pred.flatten()), inplace = True)

/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [71]:
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None)  

train_X_monetary = train[['X1_m1','X2_m1','X3_m1','X4_m1','X5_m1','X6_m1','X7_m1','X8_m1',
                          'X1_m2','X2_m2','X3_m2','X4_m2','X5_m2','X6_m2','X7_m2','X8_m2',
                          'X1_m3','X2_m3','X3_m3','X4_m3','X5_m3','X6_m3','X7_m3','X8_m3']]

train_X_monetary = train_X_monetary.replace(0, np.NaN)

train_X_monetary= train_X_monetary.median(axis= 'columns')
pd.options.display.float_format = '{:.2f}'.format
train['Monetary_median'] = train_X_monetary

In [72]:
train.head()

,cust_no,label,E1,E2,E3,E4,E5,E6,E10,E14,E15,E16,E17,E18,I1,I2,I3,I4,I6,I7,I11,I15,I16,I17,I18,I19,I20,X1_m1,X2_m1,X3_m1,X4_m1,X5_m1,X6_m1,X7_m1,X8_m1,B1_m1,B2_m1,B3_m1,B4_m1,B5_m1,C1_m1,C2_m1,X1_m2,X2_m2,X3_m2,X4_m2,X5_m2,X6_m2,X7_m2,X8_m2,B1_m2,B2_m2,B3_m2,B4_m2,B5_m2,C1_m2,C2_m2,X1_m3,X2_m3,X3_m3,X4_m3,X5_m3,X6_m3,X7_m3,X8_m3,B1_m3,B2_m3,B3_m3,B4_m3,B5_m3,B6_m3,B7_m3,C1_m3,C2_m3,Recency,Time,last_Date,first_Date,군인,농축업,무직,사무원,생산직,서비스직,은퇴,전문직,정치인,판매원,프리랜서,Monetary_median
0,0xb2d30bf6,1.00,790,789,789,0,0,168,1,18169,18169,0,0.00,0,1.00,58.00,4,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,0.00,0.00,15774.75,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,15774.75,1.00,0.00,0.00,19449.75,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19449.75,1.00,0.00,0.00,23140.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,18,3.00,23140.95,1.00,149,1206,2019-09-11 18:00:00,2019-04-15,0,0,0,0,0,1,0,0,0,0,0,19449.75
1,0xb2d0c143,1.00,1538,1538,1538,1,1,353,263,18168,18169,0,0.00,0,0.00,29.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,110000.00,0.00,20000.30,0.00,0.00,0.00,0.00,0.00,8.00,5.00,240533.36,2.00,110000.00,130000.30,3.00,130000.00,0.00,0.30,0.00,0.00,0.00,0.00,0.00,5.00,1.00,20000.00,1.00,20000.00,130000.30,4.00,170000.00,0.00,94.56,0.00,0.00,0.00,0.00,0.00,11.00,2.00,80084.44,1.00,60000.00,10,21.00,170094.56,4.00,342,1198,2019-09-19 05:04:00,2018-10-12,0,0,0,0,0,0,0,0,0,0,1,65000.15
2,0xb2d6004d,1.00,305,305,305,0,0,305,175,18169,18169,0,0.00,0,0.00,63.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,70000.00,0.00,13.93,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70013.93,3.00,70000.00,0.00,13.93,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70013.93,3.00,70000.00,0.00,13.94,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,163,0.00,70013.94,3.00,141,1351,2019-04-19 04:03:00,2018-11-29,0,0,0,1,0,0,0,0,0,0,0,35006.97
3,0xb2d5a839,1.00,356,356,356,0,1,332,284,18168,18168,1,20000.00,1,0.00,29.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,153000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,81000.00,1.00,81000.00,153000.00,3.00,153000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,153000.00,3.00,81000.00,0.00,42812.32,0.00,0.00,0.00,0.00,0.00,7.00,1.00,72803.60,1.00,30000.00,18,4.00,123812.32,2.00,313,1206,2019-09-11 15:40:00,2018-11-02,0,0,0,0,0,0,0,0,0,1,0,117000.00
5,0xb2d6d3ac,-1.00,160,160,160,1,1,154,1,18168,18168,1,1500000.00,1,1.00,48.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00,366.70,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,366.70,1.00,0.00,0.00,500366.70,0.00,0.00,0.00,0.00,0.00,11.00,0.00,0.00,0.00,0.00,500366.70,1.00,0.00,0.00,398.72,0.00,0.00,0.00,0.00,0.00,8.00,0.00,0.00,3.00,500000.00,26,4.00,398.72,1.00,127,1214,2019-09-03 14:33:00,2019-04-29,0,0,0,0,0,0,0,0,0,0,1,398.72

In [73]:


# X열의 모든 열을 1개의 변수로 차원축소 
X_df= train[['X1_m1','X2_m1','X3_m1','X4_m1','X5_m1','X6_m1','X7_m1','X8_m1',
              'X1_m2','X2_m2','X3_m2','X4_m2','X5_m2','X6_m2','X7_m2','X8_m2',
              'X1_m3','X2_m3','X3_m3','X4_m3','X5_m3','X6_m3','X7_m3','X8_m3']]

from sklearn.preprocessing import StandardScaler 
from sklearn.decomposition import PCA

scaler = StandardScaler() 
data_scaled = scaler.fit_transform(X_df)

pca = PCA(n_components = 1)  
pca.fit(data_scaled)  
df_pca = pca.transform(data_scaled)  
print(df_pca.shape)  

# 1차원으로 줄인 단일변수의 설명력 
print(pca.explained_variance_ratio_) 
 
train['X_pca'] = df_pca 
train.head()

(130654, 1)
[0.14325143]

,cust_no,label,E1,E2,E3,E4,E5,E6,E10,E14,E15,E16,E17,E18,I1,I2,I3,I4,I6,I7,I11,I15,I16,I17,I18,I19,I20,X1_m1,X2_m1,X3_m1,X4_m1,X5_m1,X6_m1,X7_m1,X8_m1,B1_m1,B2_m1,B3_m1,B4_m1,B5_m1,C1_m1,C2_m1,X1_m2,X2_m2,X3_m2,X4_m2,X5_m2,X6_m2,X7_m2,X8_m2,B1_m2,B2_m2,B3_m2,B4_m2,B5_m2,C1_m2,C2_m2,X1_m3,X2_m3,X3_m3,X4_m3,X5_m3,X6_m3,X7_m3,X8_m3,B1_m3,B2_m3,B3_m3,B4_m3,B5_m3,B6_m3,B7_m3,C1_m3,C2_m3,Recency,Time,last_Date,first_Date,군인,농축업,무직,사무원,생산직,서비스직,은퇴,전문직,정치인,판매원,프리랜서,Monetary_median,X_pca
0,0xb2d30bf6,1.00,790,789,789,0,0,168,1,18169,18169,0,0.00,0,1.00,58.00,4,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,0.00,0.00,15774.75,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,15774.75,1.00,0.00,0.00,19449.75,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19449.75,1.00,0.00,0.00,23140.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,18,3.00,23140.95,1.00,149,1206,2019-09-11 18:00:00,2019-04-15,0,0,0,0,0,1,0,0,0,0,0,19449.75,-0.29
1,0xb2d0c143,1.00,1538,1538,1538,1,1,353,263,18168,18169,0,0.00,0,0.00,29.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,110000.00,0.00,20000.30,0.00,0.00,0.00,0.00,0.00,8.00,5.00,240533.36,2.00,110000.00,130000.30,3.00,130000.00,0.00,0.30,0.00,0.00,0.00,0.00,0.00,5.00,1.00,20000.00,1.00,20000.00,130000.30,4.00,170000.00,0.00,94.56,0.00,0.00,0.00,0.00,0.00,11.00,2.00,80084.44,1.00,60000.00,10,21.00,170094.56,4.00,342,1198,2019-09-19 05:04:00,2018-10-12,0,0,0,0,0,0,0,0,0,0,1,65000.15,-0.22
2,0xb2d6004d,1.00,305,305,305,0,0,305,175,18169,18169,0,0.00,0,0.00,63.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,70000.00,0.00,13.93,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70013.93,3.00,70000.00,0.00,13.93,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70013.93,3.00,70000.00,0.00,13.94,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,163,0.00,70013.94,3.00,141,1351,2019-04-19 04:03:00,2018-11-29,0,0,0,1,0,0,0,0,0,0,0,35006.97,-0.26
3,0xb2d5a839,1.00,356,356,356,0,1,332,284,18168,18168,1,20000.00,1,0.00,29.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,153000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,81000.00,1.00,81000.00,153000.00,3.00,153000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,153000.00,3.00,81000.00,0.00,42812.32,0.00,0.00,0.00,0.00,0.00,7.00,1.00,72803.60,1.00,30000.00,18,4.00,123812.32,2.00,313,1206,2019-09-11 15:40:00,2018-11-02,0,0,0,0,0,0,0,0,0,1,0,117000.00,-0.22
5,0xb2d6d3ac,-1.00,160,160,160,1,1,154,1,18168,18168,1,1500000.00,1,1.00,48.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00,366.70,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,366.70,1.00,0.00,0.00,500366.70,0.00,0.00,0.00,0.00,0.00,11.00,0.00,0.00,0.00,0.00,500366.70,1.00,0.00,0.00,398.72,0.00,0.00,0.00,0.00,0.00,8.00,0.00,0.00,3.00,500000.00,26,4.00,398.72,1.00,127,1214,2019-09-03 14:33:00,2019-04-29,0,0,0,0,0,0,0,0,0,0,1,398.72,-0.20

In [74]:
'''
원본 train- 즉, x변수를 차원축소하지 않은채로의 예측 모델의 정확도 살펴보기 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.model_selection import GridSearchCV 

rfc = RandomForestClassifier(random_state =42)  

param_grid = {
    'n_estimators' : [200, 500],
    'max_features' : ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8], 
    'criterion' : ['gini', 'entropy']
}

CV_rfc = GridSearchCV(estimator = rfc, param_grid = param_grid, cv =5)  
CV_rfc.fit(train.iloc[:,2:], train.label)

CV_rfc.best_params_

'''

"\n원본 train- 즉, x변수를 차원축소하지 않은채로의 예측 모델의 정확도 살펴보기 \nfrom sklearn.ensemble import RandomForestClassifier \nfrom sklearn.model_selection import GridSearchCV \n\nrfc = RandomForestClassifier(random_state =42)  \n\nparam_grid = {\n    'n_estimators' : [200, 500],\n    'max_features' : ['auto', 'sqrt', 'log2'],\n    'max_depth' : [4,5,6,7,8], \n    'criterion' : ['gini', 'entropy']\n}\n\nCV_rfc = GridSearchCV(estimator = rfc, param_grid = param_grid, cv =5)  \nCV_rfc.fit(train.iloc[:,2:], train.label)\n\nCV_rfc.best_params_\n\n"

In [75]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import warnings
import os 

from datetime import datetime 
from datetime import timedelta

from lifetimes.plotting import * 
from lifetimes.utils import * 
from lifetimes import BetaGeoFitter 
from lifetimes.fitters.gamma_gamma_fitter import GammaGammaFitter  

from hyperopt import hp, fmin, tpe, rand, SparkTrials, STATUS_OK, space_eval, Trials

In [76]:
train.head()

,cust_no,label,E1,E2,E3,E4,E5,E6,E10,E14,E15,E16,E17,E18,I1,I2,I3,I4,I6,I7,I11,I15,I16,I17,I18,I19,I20,X1_m1,X2_m1,X3_m1,X4_m1,X5_m1,X6_m1,X7_m1,X8_m1,B1_m1,B2_m1,B3_m1,B4_m1,B5_m1,C1_m1,C2_m1,X1_m2,X2_m2,X3_m2,X4_m2,X5_m2,X6_m2,X7_m2,X8_m2,B1_m2,B2_m2,B3_m2,B4_m2,B5_m2,C1_m2,C2_m2,X1_m3,X2_m3,X3_m3,X4_m3,X5_m3,X6_m3,X7_m3,X8_m3,B1_m3,B2_m3,B3_m3,B4_m3,B5_m3,B6_m3,B7_m3,C1_m3,C2_m3,Recency,Time,last_Date,first_Date,군인,농축업,무직,사무원,생산직,서비스직,은퇴,전문직,정치인,판매원,프리랜서,Monetary_median,X_pca
0,0xb2d30bf6,1.00,790,789,789,0,0,168,1,18169,18169,0,0.00,0,1.00,58.00,4,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,0.00,0.00,15774.75,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,15774.75,1.00,0.00,0.00,19449.75,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19449.75,1.00,0.00,0.00,23140.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,18,3.00,23140.95,1.00,149,1206,2019-09-11 18:00:00,2019-04-15,0,0,0,0,0,1,0,0,0,0,0,19449.75,-0.29
1,0xb2d0c143,1.00,1538,1538,1538,1,1,353,263,18168,18169,0,0.00,0,0.00,29.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,110000.00,0.00,20000.30,0.00,0.00,0.00,0.00,0.00,8.00,5.00,240533.36,2.00,110000.00,130000.30,3.00,130000.00,0.00,0.30,0.00,0.00,0.00,0.00,0.00,5.00,1.00,20000.00,1.00,20000.00,130000.30,4.00,170000.00,0.00,94.56,0.00,0.00,0.00,0.00,0.00,11.00,2.00,80084.44,1.00,60000.00,10,21.00,170094.56,4.00,342,1198,2019-09-19 05:04:00,2018-10-12,0,0,0,0,0,0,0,0,0,0,1,65000.15,-0.22
2,0xb2d6004d,1.00,305,305,305,0,0,305,175,18169,18169,0,0.00,0,0.00,63.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,70000.00,0.00,13.93,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70013.93,3.00,70000.00,0.00,13.93,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70013.93,3.00,70000.00,0.00,13.94,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,163,0.00,70013.94,3.00,141,1351,2019-04-19 04:03:00,2018-11-29,0,0,0,1,0,0,0,0,0,0,0,35006.97,-0.26
3,0xb2d5a839,1.00,356,356,356,0,1,332,284,18168,18168,1,20000.00,1,0.00,29.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,153000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,81000.00,1.00,81000.00,153000.00,3.00,153000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,153000.00,3.00,81000.00,0.00,42812.32,0.00,0.00,0.00,0.00,0.00,7.00,1.00,72803.60,1.00,30000.00,18,4.00,123812.32,2.00,313,1206,2019-09-11 15:40:00,2018-11-02,0,0,0,0,0,0,0,0,0,1,0,117000.00,-0.22
5,0xb2d6d3ac,-1.00,160,160,160,1,1,154,1,18168,18168,1,1500000.00,1,1.00,48.00,3,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00,366.70,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,366.70,1.00,0.00,0.00,500366.70,0.00,0.00,0.00,0.00,0.00,11.00,0.00,0.00,0.00,0.00,500366.70,1.00,0.00,0.00,398.72,0.00,0.00,0.00,0.00,0.00,8.00,0.00,0.00,3.00,500000.00,26,4.00,398.72,1.00,127,1214,2019-09-03 14:33:00,2019-04-29,0,0,0,0,0,0,0,0,0,0,1,398.72,-0.20

1. 고객별 RFMT를 구하기

In [77]:
train_RFTM = train[['cust_no', 'B7_m3', 'Recency', 'Time', 'last_Date','first_Date', 'Monetary_median']]  

train_RFTM.rename(columns = {'B7_m3' : 'Frequency', 'Monetary_median': 'Monetary'}, inplace = True)  
 
train_RFTM.shape

(130654, 7)

In [78]:
train_RFTM.head()

,cust_no,Frequency,Recency,Time,last_Date,first_Date,Monetary
0,0xb2d30bf6,3.00,149,1206,2019-09-11 18:00:00,2019-04-15,19449.75
1,0xb2d0c143,21.00,342,1198,2019-09-19 05:04:00,2018-10-12,65000.15
2,0xb2d6004d,0.00,141,1351,2019-04-19 04:03:00,2018-11-29,35006.97
3,0xb2d5a839,4.00,313,1206,2019-09-11 15:40:00,2018-11-02,117000.00
5,0xb2d6d3ac,4.00,127,1214,2019-09-03 14:33:00,2019-04-29,398.72

In [80]:
train_RFTM.sort_values(by='Frequency', ascending = False).head()

,cust_no,Frequency,Recency,Time,last_Date,first_Date,Monetary
58165,0xb2d586db,5043.00,98,1187,2019-09-30 21:54:00,2019-06-24,1596.40
58165,0xb2d586db,4048.00,16,1095,2019-12-31 21:51:00,2019-12-15,4436.30
52511,0xb2d6dc7b,3990.00,2,1119,2019-12-07 00:15:00,2019-12-05,3226.67
34054,0xb2d29bfb,3708.00,32,1095,2019-12-31 21:10:00,2019-11-29,4911.18
46574,0xb2d5bde3,3579.00,62,1095,2019-12-31 16:40:00,2019-10-30,1729.40

In [241]:
train_RFTM = train_RFTM[train_RFTM['Frequency'] > 0]  
train_RFTM.shape

(111462, 7)

### 2차 시도 ###

In [ ]:
train_RFTM[train_RFTM['Recency'] > train_RFTM['Time']]

In [242]:
bgf = BetaGeoFitter(penalizer_coef=0.001)  
bgf.fit(train_RFTM['Frequency'],
        train_RFTM['Recency'],
        train_RFTM['Time'])

In [249]:
bgf.conditional_expected_number_of_purchases_up_to_time(365,
                                                        train_RFTM['Frequency'],
                                                        train_RFTM['Recency'],
                                                        train_RFTM['Time']).sort_values(ascending=False).head(10)

26489   0.94
23833   0.89
34276   0.88
40878   0.87
47874   0.86
46676   0.86
20669   0.85
4824    0.85
12332   0.85
14261   0.84
dtype: float64


2. calibration/holdout 데이터를 나눠 L2 penalty 최적화 하기

In [76]:
# 우리 데이터는 2017.2.1 ~ 2019.12.31 까지 존재하여 2:1로 대략 360일을 기준으로 훈련/테스트 셋 나누기  
holdout_days = 360
current_date = pd.to_datetime('2020-1-1')  
calibration_end_date = current_date - timedelta(days= holdout_days) 

metrics_cal_df = calibration_and_holdout_data(train_RFTM, 
                                              customer_id_col = 'cust_no' 
                                              ,datetime_col = 'first_Date'
                                              ,calibration_period_end = calibration_end_date
                                              ,observation_period_end = current_date
                                              ,monetary_value_col= 'Monetary')
metrics_cal_df.shape

(30009, 7)

In [77]:
metrics_cal_df.head()

,frequency_cal,recency_cal,T_cal,monetary_value_cal,frequency_holdout,monetary_value_holdout,duration_holdout
cust_no,,,,,,,
0x3b9acb2b,0.00,0.00,124.00,0.00,1.00,496892.25,360.00
0x3b9acd53,0.00,0.00,117.00,0.00,1.00,3060.77,360.00
0x3b9acd5f,1.00,69.00,368.00,1154681.83,0.00,0.00,360.00
0x3b9acde2,0.00,0.00,307.00,0.00,1.00,13108.65,360.00
0x3b9ace47,0.00,0.00,55.00,0.00,1.00,3639759.31,360.00

In [78]:
# frequency가 0이하인거 없는지 확인하기 
train_RFTM = train_RFTM[train_RFTM.Frequency > 0]  
filtered_df = metrics_cal_df[metrics_cal_df.frequency_cal > 0 ]

In [79]:
train_RFTM.shape

(111462, 7)

In [504]:
filtered_df.head()  
metrics_cal_df.shape
filtered_df.shape

,frequency_cal,recency_cal,T_cal,monetary_value_cal,frequency_holdout,monetary_value_holdout,duration_holdout
cust_no,,,,,,,
0x3b9acd5f,1.00,69.00,368.00,1154681.83,0.00,0.00,360.00
0x3b9aced9,1.00,49.00,137.00,111092.02,0.00,0.00,360.00
0x3b9acfb9,1.00,77.00,237.00,443141.68,0.00,0.00,360.00
0x3b9ad187,1.00,20.00,297.00,130000.00,0.00,0.00,360.00
0x3b9ad43c,1.00,18.00,227.00,7194.61,0.00,0.00,360.00

(30009, 7)

(7617, 7)

### 오류 발생 - 여기서부터

In [80]:

def score_model(actuals, predicted, metric ='mse'):
    
    metric = metric.lower()  
    
    # MSE /RMSE 
    if metric == 'mse' or metric == 'rmse':
        val = np.sum(np.square(actuals-predicted)/ actuals.shape[0])  
        
    elif metric == 'rmse':
        val = np.sqrt(val)  
        
    elif metric == 'mae':
        val = np.sum(np.abs(actuals-predicted)) / actuals.shape[0]  
        
    else:
        val = None  
        
    return val 

def evaluate_bgnbd_model(param):
    
    data = inputs  
    l2_reg = param  
    
    # 모형 적합
    model = BetaGeoFitter(penalizer_coef = l2_reg)  
    model.fit(data['frequency_cal'], data['recency_cal'], data['T_cal'])  
    
    #모형 평가 
    frequency_actual = data['frequency_holdout']  
    frequency_predicted = model.predict(data['duration_holdout']
                                        , data['frequency_cal']
                                        , data['recency_cal']
                                        , data['T_cal'])  
    
    mse = score_model(frequency_actual,frequency_predicted, 'mse')  
    
    return {'loss': mse, 'status' : STATUS_OK}  

def evaluate_gg_model(param):
    
    data = inputs
    l2_reg = param  
    
    model = GammaGammaFitter(penalizer_coef = l2_reg)  
    model.fit(data['frequency_cal'], data['monetary_value_cal'])  
    
    #모형 평가 
    monetary_actual = data['monetary_value_holdout']  
    monetary_predicted = model.conditional_expected_average_profit(data['frequency_holdout'], data['monetary_value_holdout'])  
    mse = score_model(monetary_actual, monetary_predicted, 'mse')  
    
    return {'loss': mse, 'status': STATUS_OK}
    
    

# model = BetaGeoFitter(penalizer_coef = l2_reg)  
#model = GammaGammaFitter(pernalizer_coef = l2_reg)

In [82]:

# hyperopt 모듈의 fmin 함수를 이용해 BG/NBD 모형과 Gamma-Gamma 모형 각각의 최적의 L2 penalty 찾기 

search_space = hp.uniform('ㅣ2', 0.0, 1.0)  
algo = tpe.suggest 
trials = Trials()  
inputs = metrics_cal_df  

argmin = fmin(
    fn = evaluate_bgnbd_model,
    space = search_space,
    algo = algo,
    max_evals =10000, 
    trials = trials
)

l2_bgnbd = space_eval(search_space, argmin)  

print(l2_bgnbd)  #이 값이 BG/NBG 모형의 최적의 L2 penalty

tirals = Trials()  

argmin = fmin(
    fn = evaluate_gg_model,
    space = search_space,
    algo= algo,
    max_evals =10000, 
    trials = trials
)

l2_gg = space_eval(search_space, argmin)  
print(l2_gg)  # 이 값은 Gamma-Gamma 모형의 최적의 L2 penalty

      fun: 0.27721318754445645
 hess_inv: array([[3.54227939e+00, 4.69288798e+00, 2.71699933e+01, 1.77687672e+02],
       [4.69288798e+00, 1.43128272e+01, 1.85342274e+01, 7.62649618e+01],
       [2.71699933e+01, 1.85342274e+01, 2.24830417e+03, 1.66031793e+04],
       [1.77687672e+02, 7.62649618e+01, 1.66031793e+04, 1.23017172e+05]])
      jac: array([-3.27731106e-04,  5.19922739e-05,  1.20833313e-04, -2.24475884e-06])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 53
      nit: 26
     njev: 41
   status: 2
  success: False
        x: array([ -1.81271456,  -2.71938296,  -4.78898931, -25.51140603])
  0%|          | 0/10000 [00:00<?, ?trial/s, best loss=?]

job exception:
The model did not converge. Try adding a larger penalizer to see if that helps convergence.

  0%|          | 0/10000 [00:00<?, ?trial/s, best loss=?]

ConvergenceError:
The model did not converge. Try adding a larger penalizer to see if that helps convergence.


3. 최적화된 값을 BG/NBD 모형에 넣어 예상 구매 일수 구하기


4. 최적화된 값을 Gamma-Gamma 모형에 넣어 예상 구매 금액을 구하기

In [509]:
lifetimes_model = BetaGeoFitter(penalizer_coef=  ) #l2_bgnbd = hyperopt로 나온 결과
# calibration 데이터의 R,F,T로 모형 적합
lifetimes_model.fit(filtered_df['frequency_cal'], filtered_df['recency_cal'], filtered_df['T_cal']) 

# holdout 데이터로 모델 평가: F의 실제값과 예측값의 MSE
frequency_actual = filtered_df['frequency_holdout']
frequency_predicted = lifetimes_model.predict(filtered_df['duration_holdout']
                                    ,filtered_df['frequency_cal']
                                    , filtered_df['recency_cal']
                                    , filtered_df['T_cal'])
mse = score_model(frequency_actual, frequency_predicted, 'mse')
print('MSE: {0}'.format(mse))

/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in power
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)

      fun: -0.18781061823853734
 hess_inv: array([[5.50420673e-01, 7.34807127e-01, 1.70059219e+01, 6.03539723e+01],
       [7.34807127e-01, 4.18416993e+00, 1.91449974e+01, 6.79147154e+01],
       [1.70059219e+01, 1.91449974e+01, 6.73559424e+04, 2.39174283e+05],
       [6.03539723e+01, 6.79147154e+01, 2.39174283e+05, 8.49296889e+05]])
      jac: array([-2.63156082e-04,  9.45050104e-06,  3.84677861e-06, -4.10194887e-08])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 139
      nit: 25
     njev: 130
   status: 2
  success: False
        x: array([ -0.82923091,  -3.25663288,  -6.55445278, -21.59311715])

/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in exp
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in subtract
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
/Users/park_jinyoung/opt/anaconda3/lib/python3.9/site-packages/autograd/numpy/numpy_vjps.py:78: RuntimeWarning: invalid value encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)

ConvergenceError:
The model did not converge. Try adding a larger penalizer to see if that helps convergence.

In [329]:
lifetimes_model.summary

AttributeError: 'BetaGeoFitter' object has no attribute 'params_'

- [참고해서 해석할 것] 해석하는 법

여기서 T 기간동안의 평균 구매 횟수가 λT이므로 λ에 대한 분포는 1일 단위입니다.

위 그림에서 0.2쯤부터 확률이 0으로 수렴하고 있는데 대부분 고객들이 1일의 평균 구매 횟수는 최대 0.2 정도임을 의미합니다. 즉, 최대 5일에 한 번 꼴로 구매한다라 볼 수도 있겠죠!  

분포가 0과 1 근처로 양극단에 위치한 것을 볼 수 있습니다. 즉 더 이상 구매를 하지 않을 확률이 0인 active한 유저도 많고, 확률이 1 근처인 inactive한 유저도 많음을 알 수 있습니다.

In [330]:
# 고객별 lambda (구매율)의 분포   


from scipy.stats import gamma  
import matplotlib.pyplot as plt  

coefs = lifetimes_model.summary['coef']  

x = np.linspace(0,2,100)  
y = gamma.pdf(x, a=coefs['r'], scale=1/coefs['alpha'])  

plt.plot(x,y)

AttributeError: 'BetaGeoFitter' object has no attribute 'params_'

In [ ]:
# 감마모형의 최적화 모형 적합하기  

spend_model = GammaGammaFitter(penalizer_coef=l2_gg)
spend_model.fit(filtered_df['frequency_cal'], filtered_df['monetary_value_cal'])

# conditional_expected_average_profit: 고객별 평균 구매 금액 예측
monetary_actual = filtered_df['monetary_value_holdout']
monetary_predicted = spend_model.conditional_expected_average_profit(filtered_df['frequency_holdout']
                                                                    ,filtered_df['monetary_value_holdout'])

mse = score_model(monetary_actual, monetary_predicted, 'mse')

print('MSE: {0}'.format(mse))


5. BG/NBD 모형과 Gamma-Gamma 모형을 합쳐 LTV를 구하기

In [ ]:
final_df = train_RFTM.copy()  

final_df['LTV'] = spend_model.customer_lifetime_value(lifetimes_model, 
                                                      final_df['Frequency'],
                                                      final_df['Recency'], 
                                                      final_df['Time'],
                                                      final_df['Monetary'], 
                                                      time = 12 # 향후 12개월 후의 LTV) 
)

# 365일 동안의 예상 구매 횟수 
t = 365 
final_df['predicted_transaction'] = lifetimes_model.conditional_expected_number_of_purchases_up_to_time(t
                                                                                     , final_df['Frequency']
                                                                                     , final_df['Recency']
                                                                                     , final_df['Time'])
)


# 예상 평균 구매금액 
final_df['predicted_monetary_value'] = spend_model.conditional_expected_average_profit(final_df['Frequency']
                                                                                      ,final_df'[Monetary_value'])

# LTV 해석
final_df.sort_values(by='LTV', ascending= False)

### **데이터 분할**
- 검증(10000), 테스트(10000)

In [ ]:

# reset train df index
train = train.reset_index(drop=True)
data_size, *_ = train.shape
train_idx = list(np.random.choice(list(set(train.index)), data_size - 20000, replace = False))
valid_idx = list(np.random.choice(list(set(train.index) - set(train_idx)), 10000, replace = False))
test_idx = list(set(train.index) - set(train_idx) - set(valid_idx))
train_data = train.iloc[train_idx]
valid_data = train.iloc[valid_idx]
test_data  = train.iloc[test_idx]
print("train_data : ", train_data.shape)
print("valid_data : ",valid_data.shape)
print("test_data : ",test_data.shape)
set(train.index) - set(train_idx) - set(valid_idx) - set(test_idx)
train_data.to_csv('../data/preprocessed_data/train_data.csv', index = False)
valid_data.to_csv('../data/preprocessed_data/valid_data.csv', index = False)
test_data.to_csv('../data/preprocessed_data/test_data.csv', index = False)